source "https://rubygems.org"

rails_version = ENV["RAILS_VERSION"]
if rails_version && !rails_version.empty?
  gem "rails", "~> #{rails_version}.0"
else
  gem "rails", ">= 7.2", "< 8.1"
end

gem "sqlite3", "~> 2.0"
gem "puma", "~> 6.0"
